Repository lambdalabs-eu1-webchat/webchat-guest-client, pull requests merged in 2019-05, with the labels that each got.

#6 stay logged in on refresh
  src/App.js
  src/components/RatingMessage.js
  src/views/ChatView.js
  src/views/LoginView.js
Labels: bug

#8 Changed url and some of Antonio's styles
  src/components/Messages.js
  src/index.css
  src/utils/constants.js
  src/views/ChatView.js
  src/views/LoginView.js
Labels: bug

#9 Favicon and tittle
  public/favicon.ico
  public/index.html
  src/index.css
  src/views/ChatView.js
Labels: bug

#10 Show typing
  src/utils/constants.js
  src/views/ChatView.js
Labels: enhancement

#13 fixing making a new ticket bug
  src/utils/constants.js
  src/views/ChatView.js
Labels: bug

#12 Populate login creds from QR link
  package-lock.json
  package.json
  src/views/LoginView.js
  yarn.lock
Labels: enhancement

#15 fix domain
  src/utils/constants.js
Labels: bug

#16 Guest client style2
  src/App.js
  src/components/Message.js
  src/components/MessageComposer.js
  src/components/Messages.js
  src/components/navbar/NavBar.js
  src/components/navbar/logo2.svg
  src/index.css
  src/theme/styledTheme.js
  src/utils/constants.js
  src/views/ChatView.js
  src/views/LoginView.js
Labels: styling

#20 Styling changes for guest client
  .gitignore
  public/favicon.ico
  public/index.html
  src/components/Message.js
  src/components/MessageComposer.js
  src/components/RatingMessage.js
  src/components/navbar/NavBar.js
  src/index.css
  src/theme/styledTheme.js
  src/views/ChatView.js
  src/views/LoginView.js
Labels: styling

#25 Several issues
  src/components/MessageComposer.js
  src/components/Messages.js
  src/components/Spinner.js
  src/components/Typing.js
  src/requests/ajax.js
  src/theme/styledTheme.js
  src/utils/constants.js
  src/views/ChatView.js
  src/views/LoginView.js
Labels: bug, enhancement, styling

#27 Increase font size and add transition to send button
  src/components/Message.js
  src/components/MessageComposer.js
  src/theme/styledTheme.js
  src/views/ChatView.js
Labels: styling

#28 Added Title Case to Names
  src/components/Message.js
  src/utils/titleCase.js
  src/views/ChatView.js
Labels: bug

#30 Restricted routes
  src/requests/ajax.js
  src/views/ChatView.js
Labels: HIGH

#31 now decodes html in messages
  src/components/Message.js
  src/utils/decodeHtml.js
Labels: bug

#32 Change font size for flash message and add padding
  src/views/LoginView.js
Labels: styling

#33 Shadow on Login button
  src/theme/styledTheme.js
  src/views/LoginView.js
Labels: styling
